name: Security Scan Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Git Clone
      run: |
        git clone https://github.com/JavaPanda30/FitMaxGym-App.git
        cd FitMaxGym-App

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/default

    - name: Run HTML Linter
      uses: sds100/html-linter@master
      with:
        directory: '.'
        config: '.htmlhintrc'

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
