name: Security Scan Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  sca_snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Install Snyk
      run: npm install -g snyk

    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Run Snyk to check for vulnerabilities
      run: snyk test --json > snyk_report.json || true

    - name: Upload Snyk report
      uses: actions/upload-artifact@v2
      with:
        name: snyk-report
        path: snyk_report.json

  semgrep:
    runs-on: ubuntu-latest
    needs: sca_snyk
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config auto --json > semgrep_report.json

    - name: Upload Semgrep report
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-report
        path: semgrep_report.json

    - name: Convert Semgrep report to SARIF
      run: semgrep --config auto --sarif > semgrep.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif

  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Determine scan range
      id: scan_range
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          BASE="${{ github.event.before }}"
          HEAD="${{ github.event.after }}"
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          BASE="${{ github.event.pull_request.base.sha }}"
          HEAD="${{ github.event.pull_request.head.sha }}"
        else
          BASE=$(git rev-parse HEAD~10)
          HEAD="HEAD"
        fi
        echo "base=${BASE}" >> $GITHUB_OUTPUT
        echo "head=${HEAD}" >> $GITHUB_OUTPUT

    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ steps.scan_range.outputs.base }}
        head: ${{ steps.scan_range.outputs.head }}
        extra_args: --debug --only-verified --json

    - name: Print TruffleHog Output
      if: always()
      run: |
        echo "TruffleHog Scan Results:"
        if [ -f trufflehog-results.json ]; then
          cat trufflehog-results.json
        else
          echo "No results file found. TruffleHog did not detect any issues."
        fi
        echo "End of TruffleHog Scan Results"

    - name: Upload TruffleHog results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: trufflehog-results
        path: trufflehog-results.json
        if-no-files-found: ignore

  talisman:
    runs-on: ubuntu-latest
    needs: [sca_snyk, semgrep, trufflehog]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Talisman
      run: |
        curl https://thoughtworks.github.io/talisman/install.sh | bash

    - name: Verify Talisman Installation
      run: |
        if ! command -v talisman &> /dev/null
        then
          echo "Talisman could not be found"
          exit 1
        fi

    - name: Run Talisman scan
      run: talisman --scan

    - name: Upload Talisman report
      uses: actions/upload-artifact@v2
      with:
        name: talisman-report
        path: talisman-report.json
